"""refactor freebie to global

Revision ID: 25a5aa525cbb
Revises: 88f424a7a2de
Create Date: 2026-03-08 05:08:18.507077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '25a5aa525cbb'
down_revision: Union[str, Sequence[str], None] = '88f424a7a2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_freebies')
    op.add_column('orders', sa.Column('net_total_at_check', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'net_total_at_check')
    op.create_table('order_freebies',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('freebie_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['freebie_id'], ['freebies.id'], name=op.f('order_freebies_ibfk_2')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_freebies_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
