"""create tables

Revision ID: 4cafcce1b777
Revises: 9848378cff53
Create Date: 2026-03-08 16:22:09.319025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cafcce1b777'
down_revision: Union[str, Sequence[str], None] = '9848378cff53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item_freebies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('freebie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['freebie_id'], ['freebies.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order_payments', sa.Column('installment_type', sa.String(length=50), nullable=True))
    op.add_column('order_payments', sa.Column('installment_months', sa.Integer(), nullable=True))
    op.add_column('order_payments', sa.Column('paid_date', sa.DateTime(), nullable=True))
    op.add_column('order_payments', sa.Column('paid_note', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('tracking_number', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('net_total_at_check', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('invoice_name', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('invoice_tax_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('invoice_address', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('invoice_text', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('shipping_note', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('pageName', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('installment_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'installment_type')
    op.drop_column('orders', 'pageName')
    op.drop_column('orders', 'shipping_note')
    op.drop_column('orders', 'note')
    op.drop_column('orders', 'invoice_text')
    op.drop_column('orders', 'invoice_address')
    op.drop_column('orders', 'invoice_tax_id')
    op.drop_column('orders', 'invoice_name')
    op.drop_column('orders', 'net_total_at_check')
    op.drop_column('orders', 'tracking_number')
    op.drop_column('order_payments', 'paid_note')
    op.drop_column('order_payments', 'paid_date')
    op.drop_column('order_payments', 'installment_months')
    op.drop_column('order_payments', 'installment_type')
    op.drop_table('order_item_freebies')
    # ### end Alembic commands ###
