"""refactor freebie to global

Revision ID: b53bcdaeedfd
Revises: c5cba03c28f6
Create Date: 2026-02-12 23:40:05.349636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b53bcdaeedfd'
down_revision: Union[str, Sequence[str], None] = 'c5cba03c28f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freebies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    #op.drop_table('product_freebies')
    op.add_column('order_item_freebies', sa.Column('freebie_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_item_freebies', 'freebies', ['freebie_id'], ['id'])
    op.drop_column('order_item_freebies', 'freebie_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item_freebies', sa.Column('freebie_name', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'order_item_freebies', type_='foreignkey')
    op.drop_column('order_item_freebies', 'freebie_id')
   # op.create_table('product_freebies',
   # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
   # sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True),
   # sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
   # sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_freebies_ibfk_1')),
   # sa.PrimaryKeyConstraint('id'),
   # mysql_collate='utf8mb4_0900_ai_ci',
   # mysql_default_charset='utf8mb4',
   # mysql_engine='InnoDB'
   # )
    op.drop_table('freebies')
    # ### end Alembic commands ###
