"""add invoice and installment fields

Revision ID: c5cba03c28f6
Revises: 01df68a561cf
Create Date: 2026-02-12 19:56:14.485819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5cba03c28f6'
down_revision: Union[str, Sequence[str], None] = '01df68a561cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('installment_months', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'installment_months')
    # ### end Alembic commands ###
