"""refactor freebie to global

Revision ID: c9b65c716b8d
Revises: a2eaed8294af
Create Date: 2026-02-17 11:21:15.018962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c9b65c716b8d'
down_revision: Union[str, Sequence[str], None] = 'a2eaed8294af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_freebies')
    op.add_column('order_payments', sa.Column('paid_date', sa.DateTime(), nullable=True))
    op.add_column('order_payments', sa.Column('paid_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_payments', 'paid_note')
    op.drop_column('order_payments', 'paid_date')
    op.create_table('order_freebies',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('freebie_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['freebie_id'], ['freebies.id'], name=op.f('order_freebies_ibfk_2')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_freebies_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
